# Generated by Django 2.1.3 on 2019-01-02 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SingUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('full_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre Completo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Marca de Tiempo')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
            ],
            options={
                'verbose_name': 'Carta',
                'verbose_name_plural': 'Cartas',
            },
        ),
    ]
