# Generated by Django 2.1.5 on 2019-02-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singup',
            options={'verbose_name': 'SingUp', 'verbose_name_plural': 'SingUps'},
        ),
        migrations.AlterField(
            model_name='singup',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
    ]
